-- CREATE DATABASE IF NOT EXISTS `chatting`;

-- USE `chatting`;

CREATE TABLE IF NOT EXISTS `room`
(
    `id`         BIGINT AUTO_INCREMENT PRIMARY KEY,
    `name`       VARCHAR(255) NOT NULL UNIQUE,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `chat`
(
    `id`         BIGINT AUTO_INCREMENT PRIMARY KEY,
    `room`       VARCHAR(255) NOT NULL COMMENT 'Room name',
    `name`       VARCHAR(255) NOT NULL,
    `message`    TEXT         NOT NULL,
    `send_time`  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `server_info`
(
    `ip`        VARCHAR(255) NOT NULL PRIMARY KEY,
    `available` BOOLEAN      NOT NULL
);
